### PR TITLE
Add "select all" and animation to brush

### LINKED ISSUE #19: Add "select all" or animation to brush

### PR DESCRIPTION
**Pull request by PhilipMathieu**
Fixes #19

### CODE REVIEW

**Comment by PhilipMathieu** [comment]
Video demonstrating new features:
https://user-images.githubusercontent.com/3598004/205678566-024c06e0-afe7-4c6e-930c-965c3cc91960.mp4

**Comment by nwebb-roux** [comment]
@PhilipMathieu Is the code change here just updated the version number of the Observable notebook? It's got a big conflict with main, but I assume that's just because of the HTML cleanup in main.

**Comment by nwebb-roux** [comment]
No worries, just ping us once you've pushed the changes!

**Comment by PhilipMathieu** [comment]
Okay it's good to review now. The changes are:
- On the Observable end, modifying the compass and brush to be able to send them custom events (e.g., "animate" or "select all")
- In `index.html`, modifying div positions to make space for the new Animate and Select All buttons
- Adding the corresponding JS to inject the buttons
- Refactoring the embed JS to be a little bit more concise

**Review by nwebb-roux — APPROVED** [review]

**Pull request merged**
