### PR TITLE
removed flyTo, brought in layer toggles

### PR DESCRIPTION
**Pull request by nwebb-roux**
I removed the FlyTo function and integrated the points of interest toggles into the site, so that the top of the page now looks like this:
Screen Shot 2022-12-10 at 11 49 59 AM

This should complete issue #47 (unless we want to increase the map icon size) and partially complete issue #44, though we still need to integrate smell filter buttons if we want them.

### CODE REVIEW

**Review by PhilipMathieu — APPROVED** [review]
Looks good

**Comment by bergsalex** [comment]
Approving, but I'm having issues getting this feature working on my local machine.

**Review by bergsalex — APPROVED** [review]

**Comment by nwebb-roux** [comment]
@bergsalex I'll merge it into main now and roll it back if it doesn't work in the live version. What's failing on your local?

**Comment by nwebb-roux** [comment]
It's working live, in my browser at least. I'm running the latest Firefox.

**Comment by bergsalex** [comment]
It's broken for me in both firefox and chrome. The points of interest do not affect the map, and the anuimate reports over time button does not do anything.

**Comment by nwebb-roux** [comment]
@bergsalex You're absolutely right--it's broken in the latest version of the notebook. I was testing it in the older version that didn't also have Philip's compass fix. I'm looking into it now.

**Pull request merged**
