### PR TITLE
59 add better grouping for the what does it smell like bar chart

### PR DESCRIPTION
**Pull request by bergsalex**

### CODE REVIEW

**Comment by nwebb-roux** [comment]
@bergsalex Does this need a notebook version number bump, or is the added embed ID enough?

**Comment by bergsalex** [comment]
@nwebb-roux, the notebook version was already bumped above the integration of the new chart, so we should be good to go.

**Review by nwebb-roux — APPROVED** [review]

**Comment by bergsalex** [comment]
Screen Shot 2022-12-12 at 5 09 54 PM

**Review by PhilipMathieu — APPROVED** [review]
looks great

**Pull request merged**
