### PR TITLE
Use API directly in notebook

### LINKED ISSUE #29: Incorporate weather data API
- Compare changes in the main Observable notebook: https://observablehq.com/compare/e5057433bd482160@950...e5057433bd482160@1106
- Separate notebook with the API calls: https://observablehq.com/d/c16cbf71c8623c43

### PR DESCRIPTION
**Pull request by PhilipMathieu**
Fixes #29

### CODE REVIEW

**Comment by bergsalex** [comment]
Approved this and then noticed that PR #31 seems to override this PR.

**Comment by PhilipMathieu** [comment]
@bergsalex the new pull request does override this, but fixes a separate issue. Unneccessary but sort of leaves "breadcrumbs" on which versions of the Observable notebook added what functionality

**Comment by bergsalex** [comment]
Makes sense. I wish observable had better git integration.

**Comment by nwebb-roux** [comment]
Resolved the merge conflict by using the more recent Observable notebook reference (@1118) that was already in main. So this PR won't actually change anything, but at least it'll be on the record.

**Pull request merged**
