### PR TITLE
Fork Smell My City API code from ds5110/stinky2 and update to run automatically with GitHub Actions

### PR DESCRIPTION
**Pull request by PhilipMathieu**

### CODE REVIEW

**Comment by bergsalex** [comment]
Isn't that CSV file committed to source going to get out of hand? Now sure how many lines it is, but if we include large data files, especially those that change a lot, git can get really really slow. 

Maybe we should host the data file in Object Storage, like S3 or GCP Cloud Storage?

**Comment by pbogden** [comment]
I think Nat is going to make this a dynamic link. The API seems pretty good, apparently

**Comment by PhilipMathieu** [comment]
Directly accessing data from the underlying API in the vein of https://observablehq.com/d/c16cbf71c8623c43 is a better approach

**Comment by bergsalex** [comment]
@PhilipMathieu @pbogden We could always remove the github actions pipelines and leave the python code. It seems useful even if it's not how we actually compute the values in production.

**Pull request closed without merging**
